name: qanswer
description: "Education CRUD system."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # DATABASE
  sqflite: ^2.3.0
  path: ^1.8.3

  # FILE & SHARE
  file_picker: ^8.0.0
  share_plus: ^10.0.0

  # FIREBASE
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

  # 🔥 LOCAL STORAGE (FOR FONT / THEME / SETTINGS SAVE)
  shared_preferences: ^2.2.3
  
  flutter_math_fork: ^0.7.4

  # 🆕 AUTO SCROLLING TEXT PACKAGE
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ➕ অ্যাপ আইকন চেঞ্জ করার প্যাকেজ এখানে যোগ করা হয়েছে
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# ➕ অ্যাপ আইকনের কনফিগারেশন এখানে যোগ করা হয়েছে
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png" # আপনার আইকন ইমেজের পাথ (প্রয়োজনে নাম পরিবর্তন করে নিবেন)