name: qanswer
description: "A new Flutter project for education CRUD system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # ডাটাবেস ব্যবহারের জন্য
  sqflite: ^2.3.0
  path: ^1.8.3

  # ডাটাবেস ফাইল এক্সপোর্ট/শেয়ার করার জন্য
  share_plus: any

  # ব্যাকআপ ফাইল সিলেক্ট বা ইমপোর্ট করার জন্য
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
